-- 1
UPDATE ENDERECO 
SET LOGRADOURO = 'skdmdls', COMPLEMENTO = 'dksdlfsk'
WHERE ID_ENDERECO = 1;
--2
UPDATE ENDERECO 
SET numero = 999999 WHERE ID_ENDERECO  = 4;
--3
DELETE FROM ENDERECO WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM ENDERECO);
--4
DELETE FROM ENDERECO e WHERE NUMERO = 999999;
--5
DELETE FROM ENDERECO;

--========================== Exercicios de JOIN ========================

--1 Cross join pessoa e contato 
SELECT * FROM PESSOA P CROSS JOIN CONTATO;

--2 Inner join pessoa e contato 
SELECT P.NOME,P.CPF, C.ID_CONTATO, C.NUMERO FROM PESSOA P INNER JOIN CONTATO C ON
P.ID_PESSOA  = C.ID_PESSOA;

---- 3 Inner pessoa, pessoa X pessoa_endereco, endereco_pessoa
SELECT p.nome, p.CPF, ep.LOGRADOURO, ep.COMPLEMENTO, ep.CIDADE  FROM PESSOA p 
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe2 ON p.ID_PESSOA = pxpe2.ID_PESSOA 
INNER JOIN ENDERECO_PESSOA ep ON pxpe2.ID_ENDERECO = ep.ID_ENDERECO;


--4 inner join entre todas as tabelas pessoa/contato/ENDERECO_PESSOA/PESSOA_X_PESSOA_ENDERECO 
SELECT p.ID_PESSOA, p.NOME, ep.LOGRADOURO, c.NUMERO  
FROM 
PESSOA_X_PESSOA_ENDERECO pxpe 
INNER JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
INNER JOIN PESSOA p ON pxpe.ID_PESSOA = p.ID_PESSOA 
INNER JOIN CONTATO c ON pxpe.ID_PESSOA = c.ID_PESSOA;

-- 5 left join tabela pessoa e contato 
-- TODAS AS PESSOAS QUE TEM CONTATO
-- TODAS AS INTERSEÇÕES + O LADO ESQUERDO
SELECT * FROM PESSOA LEFT JOIN CONTATO ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA;

-- 6 Left join PESSOA PESSOA_X_PESSOA_ENDERECO ENDERECO_PESSOA 
SELECT * FROM PESSOA_X_PESSOA_ENDERECO pxpe LEFT JOIN PESSOA p 
ON pxpe.ID_PESSOA = p.ID_PESSOA 
LEFT OUTER JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

-- 7 left join todas as tabelas 
SELECT * FROM PESSOA p LEFT OUTER JOIN CONTATO c ON 
p.ID_PESSOA = c.ID_PESSOA 
LEFT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON pxpe.ID_PESSOA = c.ID_PESSOA 
LEFT OUTER JOIN ENDERECO_PESSOA EP ON pxpe.ID_ENDERECO = EP.ID_ENDERECO;
