CREATE TABLE PAIS(
	ID_PAIS NUMBER (38,0) PRIMARY KEY NOT NULL, 
	NOME varchar2(50) NOT NULL 
);

CREATE TABLE ESTADO(
	ID_ESTADO NUMBER (38,0) PRIMARY KEY NOT NULL,
	ID_PAIS NUMBER (38,0) NOT NULL,
	NOME varchar2(50) NOT NULL,
	CONSTRAINT FK_ESTADO_PAIS_CID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS)
);

CREATE TABLE CIDADE(
	ID_CIDADE NUMBER (38,0) PRIMARY KEY NOT NULL,
	ID_ESTADO NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL,
	CONSTRAINT FK_CIDADE_ESTADO_CID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE TABLE BAIRRO (
	ID_BAIRRO NUMBER (38,0) PRIMARY KEY NOT NULL,
	ID_CIDADE NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL, 
	CONSTRAINT FK_BAIRRO_CIDADE_CID_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE)
);

CREATE TABLE ENDERECO (
	ID_ENDERECO NUMBER (38,0) PRIMARY KEY NOT NULL,
	ID_BAIRRO NUMBER (38,0) NOT NULL, 
	LOGRADOURO VARCHAR2 (50) NOT NULL,
	NUMERO NUMBER (38,0) NOT NULL,
	COMPLEMENTO VARCHAR2(50), 
	CEP CHAR(9),
	CONSTRAINT FK_ENDERECO_BAIRRO_CID_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (ID_BAIRRO)
);

CREATE SEQUENCE VEM_SER.SEQ_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_CIDADE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO PAIS (ID_PAIS, NOME) VALUES (VEM_SER.SEQ_PAIS.nextval, 'Brasil');
INSERT INTO PAIS (ID_PAIS, NOME) VALUES (VEM_SER.SEQ_PAIS.nextval, 'Argentina');

--Bra
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (VEM_SER.SEQ_ESTADO.nextval, 1, 'Pernambuco');
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (VEM_SER.SEQ_ESTADO.nextval, 1, 'Rio Grande do Sul');
-- Arg
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (VEM_SER.SEQ_ESTADO.nextval, 2, 'Estado 1');
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (VEM_SER.SEQ_ESTADO.nextval, 2, 'Estado 2');

--Brasil
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (VEM_SER.SEQ_CIDADE.nextval, 1,'Recife'); 
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (VEM_SER.SEQ_CIDADE.nextval , 2,'Cachoeirinhas');
--Argentina
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (VEM_SER.SEQ_CIDADE.nextval, 3,'Cidade_Argentina1');
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (VEM_SER.SEQ_CIDADE.nextval, 4,'Cidade_Argentina2');

--Bra
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, NOME) VALUES (VEM_SER.SEQ_BAIRRO.nextval, 1,'Torre');
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, NOME) VALUES (VEM_SER.SEQ_BAIRRO.nextval, 2,'Bairro do RS');
--Argentina
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, NOME) VALUES (VEM_SER.SEQ_BAIRRO.nextval, 3,'Bairro1');
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, NOME) VALUES (VEM_SER.SEQ_BAIRRO.nextval, 4,'Bairro2');

--Bra
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES 
(VEM_SER.SEQ_ENDERECO.nextval, 1, 'Rua torre', 13, 'Casa','5428675');
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES 
(VEM_SER.SEQ_ENDERECO.nextval, 2, 'Rua das cachoeirinhas', 25, 'Casa','5428667');
--Argentina 
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES 
(VEM_SER.SEQ_ENDERECO.nextval, 3, 'Rua arg', 15, 'Casa','5428656');
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES 
(VEM_SER.SEQ_ENDERECO.nextval, 4, 'Rua arg2', 13, 'Casa','5428675');

SELECT * FROM ENDERECO ;














